server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 101.201.52.101:8848
    gateway:
      server:
        webflux:
          routes:
            - id: comment
              uri: lb://comment-service
              predicates:
                - Path=/api/comment/**
            - id: content
              uri: lb://content-service
              predicates:
                - Path=/api/content/**
            - id: novel
              uri: lb://novel-service
              predicates:
                - Path=/api/novel/**
            - id: user
              uri: lb://user-service
              predicates:
                - Path=/api/user/**