server:
  port: 8082

spring:
  application:
    name: novel-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.52.101:3306/novel?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: final-chapters123456
  cloud:
    nacos:
      server-addr: 101.201.52.101:8848
mybatis-plus:
  type-aliases-package: com.ali5669.novelserivce.domain.po
logging:
  level:
    com.ali5669.novelserivce: debug