server:
  port: 8082
fc:
  jwt:
    location: classpath:fc.jks
    alias: finalchapters
    password: final-chapters123456
    tokenTTL: 30m
spring:
  application:
    name: novel-service
  cloud:
    nacos:
      server-addr: 101.201.52.101:8848