server:
  port: 8082

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://101.200.212.91:3306/comment?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: final-chapters123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.ali5669.commentservice.domain.po # 别名扫描包
logging:
  level:
    com.ali5669.commentservice: debug