name: Build and Deploy Comment Service

on:
  push:
    branches:
      - main # 或你希望触发的分支名
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["comment-service"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Service - ${{ matrix.service }}
        run: |
          cd final-chapters-backend/${{ matrix.service }}
          mvn clean package

      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-jar
          path: final-chapters-backend/${{ matrix.service }}/target/*.jar

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_COMMENT_SERVICE }}
          username: ${{ secrets.USERNAME_COMMENT_SERVICE }}
          port: ${{ secrets.PORT_COMMENT_SERVICE }}
          key: ${{ secrets.KEY_COMMENT_SERVICE }}
          source: "final-chapters-backend/${{ matrix.service }}/target/*.jar"
          target: "/root/workspace/FinalChaptersServer"

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_COMMENT_SERVICE }}
          username: ${{ secrets.USERNAME_COMMENT_SERVICE }}
          port: ${{ secrets.PORT_COMMENT_SERVICE }}
          key: ${{ secrets.KEY_COMMENT_SERVICE }}
          command_timeout: 20s
          script: |
            ps -ef | grep *.jar | grep -v grep | awk '{print $2}' | xargs kill -9
            cd /root/workspace/FinalChaptersServer/final-chapters-backend/${{ matrix.service }}/target/
            nohup java -jar *.jar > ${{ matrix.service }}.txt 2>&1 &
            exit
