name: Build and Deploy Spring Boot Microservices

on:
  push:
    branches:
      - main  # 或你希望触发的分支名
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: user-service
            host: ${{ secrets.HOST_USER_SERVICE }}
            username: ${{ secrets.USERNAME_USER_SERVICE }}
            port: ${{ secrets.PORT_USER_SERVICE }}
            key: ${{ secrets.KEY_USER_SERVICE }}

          - service: novel-service
            host: ${{ secrets.HOST_NOVEL_SERVICE }}
            username: ${{ secrets.USERNAME_NOVEL_SERVICE }}
            port: ${{ secrets.PORT_NOVEL_SERVICE }}
            key: ${{ secrets.KEY_NOVEL_SERVICE }}
          
          - service: content-service
            host: ${{ secrets.HOST_CONTENT_SERVICE }}
            username: ${{ secrets.USERNAME_CONTENT_SERVICE }}
            port: ${{ secrets.PORT_CONTENT_SERVICE }}
            key: ${{ secrets.KEY_CONTENT_SERVICE }}
            
          - service: comment-service
            host: ${{ secrets.HOST_COMMENT_SERVICE }}
            username: ${{ secrets.USERNAME_COMMENT_SERVICE }}
            port: ${{ secrets.PORT_COMMENT_SERVICE }}
            key: ${{ secrets.KEY_COMMENT_SERVICE }}
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build Service - ${{ matrix.service }}
      run: |
        cd final-chapters-backend/${{ matrix.service }}
        mvn clean package

    - name: Upload Artifact (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.service }}-jar
        path: final-chapters-backend/${{ matrix.service }}/target/*.jar

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ matrix.host }}
        username: ${{ matrix.username }}
        port: ${{ matrix.port }}
        key: ${{ matrix.key }}
        source: "final-chapters-backend/${{ matrix.service }}/target/*.jar"
        target: "/path/to/deploy/${{ matrix.service }}"
